### ISSUE TITLE
📋 To-Do List

### ISSUE THREAD

**Issue by richardscull** [richardscull/WebDiscordStatus#1]
Some cool ideas that I have for this page. Can't guarantee that I will make them 💀

- [x] Support Games activity https://github.com/richardscull/WebDiscordStatus/commit/f93fc962f4e3f97e44c57d086848eb97cc6d4e14
- [x] Support Stream activity https://github.com/richardscull/WebDiscordStatus/commit/f93fc962f4e3f97e44c57d086848eb97cc6d4e14 ( ⚠️ Not tested )
- [ ] Maybe animated background?
- [x] Black/White theme support
- [ ] Make mobile support (interface is fucked up right now by #12 )

Will fulfill this tasks some day... Maybe 👀
